### ISSUE TITLE
Errors when following Define ASM ControlPlaneRevision 

### ISSUE THREAD

**Issue by sf-vorlov** [mathieu-benoit/acm-workshop#92] opened 2022-10-13 11:33 UTC
Hi Mathieu,

I'm trying to follow the https://github.com/mathieu-benoit/acm-workshop/blob/dc848ccc8ab9a2ebc27d5afc455844f609390564/content/service-mesh/install-asm.md#define-asm-controlplanerevision. 
However after committing to the tenant repo I'm getting the following errors:
```
  TotalErrorCount: 2
  Error:   KNV1021: No CustomResourceDefinition is defined for the type "ControlPlaneRevision.mesh.cloud.google.com" in the cluster.
Resource types that are not native Kubernetes objects must have a CustomResourceDefinition.

Config Sync will retry until a CustomResourceDefinition is defined for the type "ControlPlaneRevision.mesh.cloud.google.com" in the cluster.

source: istio-system/control-plane-configs.yaml
namespace: istio-system
metadata.name: asm-managed-stable
group: mesh.cloud.google.com
version: v1beta1
kind: ControlPlaneRevision

For more information, see https://g.co/cloud/acm-errors#knv1021
  Error:                                                          KNV1058: Resources in namespace Repos must be Namespace-scoped type, but objects of type /v1, Kind=Namespace are Cluster-scoped. Move istio-system to the Root repo.

source: istio-system/namespace.yaml
metadata.name: istio-system
group:
version: v1
kind: Namespace

For more information, see https://g.co/cloud/acm-errors#knv1058
```

Any advise?

Thanks

**Comment by mathieu-benoit** [comment] 2022-10-13 13:06
Thanks for reporting the issue @sf-vorlov, much appreciated. I'm trying to reproduce the issue and will get back to you as soon as I can and I made progress on this. Bear with me please, thanks!

**Comment by sf-vorlov** [comment] 2022-10-13 23:15
Hi @mathieu-benoit. Thank you for responding. I've found an issue - and it is at my end. I've incorrectly configured the intended rootsync repo as a repo-sync for the config controller. My bad.

**Comment by mathieu-benoit** [comment] 2022-10-13 23:52
Thanks for following up @sf-vorlov. Glad you found out where the issue was coming from. I was going to answer that I was not able to reproduce the issue on a brand new setup.
Is there anything in the steps of the workshop that would have avoid this issue? Wondering if I can improve some documentation around this to avoid any frictions or issues like this. Thanks for sharing your thoughts on this!

_Note: not related to this, but just heads up that the https://acm-workshop.alwaysupalwayson.com/ website is temporary down, maintenance in progress on this, will keep you posted as soon as it's back._

**Comment by mathieu-benoit** [comment] 2022-10-14 00:35
FYI the website https://acm-workshop.alwaysupalwayson.com/ is back.

Closing this issue as per your last comment, but if you still have the issue feel free to re-open it and open a new one. Feedback are really more than welcome too, cheers!

**Closed by mathieu-benoit** 2022-10-14 00:35 UTC
Labels: bug

**Comment by sf-vorlov** [comment] 2022-10-14 06:27
Thanks @mathieu-benoit. The website is very helpful, indeed! Now I understand where my confusion came from. Somehow I thought the repo mentioned here https://acm-workshop.alwaysupalwayson.com/tenant-project/set-up-gke-project-git-repo/ is the same as https://acm-workshop.alwaysupalwayson.com/gke-cluster/set-up-gke-configs-git-repo/

**Comment by mathieu-benoit** [comment] 2022-10-14 11:36
Oh ok gotcha, I will think if there is anything I could clarify in the workshop around this in the instructions/steps. There is 5 different  repos, so yeah I can understand that sometimes we could ask ourself "in which repo I'm doing this again?". Good feedback, thanks!
